[package]
name = "astarte_sdk"
version = "0.1.0"
authors = ["Riccardo Binetti"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
thiserror = "1.0"